### ISSUE TITLE
Error when assigning TSup_nominal in case of multiple zones

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/BESMod#17]
If the model has multiple zones, there is an error in the assignment of TSup_nominal. 

In the Transfer model there is a parameter TSup_nominal[nParallelSup].
In PartialBuildingEnergySystem, this is set equal to TSup_nominal = SystemParameters.THydSup_nom, which is originally defined as THydSup_nominal[nZones]. 
If nParallelSup and nZones are not equal, an error occurs. 

To avoid the error, TSup_nom should be split into two parameters: 
- TSup_nominal[nParallelSup] (actual supply temperatures from generation).
- TTran_nominal[nParallelDem] (supply temperatures for transfer systems (e.g. radiators or underfloor heating).

Within the Transfer model, the maximum temperature of the transmission systems should then be used for the temperature of the supply systems as follows: 
TSup_nominal[nParallelSup] = fill(max(TTran_nominal),nParallelSup)

Translated with www.DeepL.com/Translator (free version)

**Comment by FWuellhorst** [comment]
This is not yet done, as Q_flow and m_flow are also affected.

**Comment by FWuellhorst** [comment]
Should be closed by #23
