### ISSUE TITLE
Add CI 

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/BESMod#2]
**What is the problem?**

CI is missing

**How do we want to solve it? Describe the solution you'd like**

Add CI

**Comment by FWuellhorst** [comment]
@DaJansenGit Whats the status on this?

**Comment by DaJansenGit** [comment]
Basic implementation is done. Currently, we restructure our templates. Afterwards, I will reopen this branc hand update the CI implementation in this repository as well.
