### ISSUE TITLE
Wrong calculation of ground area of the building

### ISSUE THREAD

**Issue by Mov0** [RWTH-EBC/BESMod#48]
In BESMod.Systems.Demand.Building.TEASERThermalZone the parameter ABui "Ground area of building" is by default calculated using the formula "2*sum(zoneParam.VAir)^(1/3)". This does not make much sense as the unit of the solution to this formula would be in meter when it should be square meter.
![grafik](https://user-images.githubusercontent.com/81047322/214620968-2517d414-6307-4d05-8297-3da6ed4d9f01.png)

**Comment by FWuellhorst** [comment]
That is correct. Sorry for not seeing this issue earlier. 

I tried some better simplifications, but could not find a fitting solution for these parameters based on the data TEASER gives. 
The only place where this is used is inside the pressure loss calculation of the transfer system. Currently, power consumption by all movers are not valid, as the pressure differences are not calibrated. 

I will check if we can get more TEASER output. As the floor is not always present, AZone and VAir are sadly the only parameters we can use.
Assuming a quadratic building shape, `ABui= sum(zoneParam.VAir)^(2/3)`. This assumption is obviously dangerous, but better than nothing.

**Comment by tstorek** [comment]
Just a thought. Would it be easier to derive the GroundArea from the ZoneArea or the FloorArea `Afloor` and the number of floors `nfloors`? I only checked at https://github.com/RWTH-EBC/BESMod/blob/main/BESMod/Systems/Demand/Building/RecordsCollection/RefAachen.mo I currently, do not have the documentation by hand. When I look at the values it is a little confusing to me :D

**Comment by FWuellhorst** [comment]
`nFloor` is the number of rcParams. 

Short answer: No, the thermalZone just does not allow these parameters.

The fix for this issue is to remove the default. If you use models like `RadiatorPressureBased`, you are obviously interested in pressure losses and you should therefore think about the building geometry when creating the model.
All ideal pressure-less transfer systems work with ABui=0 and hBui=0. Thus, this will be the new default.

**Comment by FWuellhorst** [comment]
I will also add an option to export from TEASER to BESMod to enable such parameters directly:
https://github.com/RWTH-EBC/TEASER/issues/733
