### ISSUE TITLE
Add HOM to Buildings

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/BESMod#6]
This issue adresses the integration of the high order approach from the AixLib into the model structure of this library. 

A model with all necessary ports and inputs should be added in order to integrate different building models based on the high order approach. 

This includes: 
- Weather data 
- Internal gains
- Heat port for convective and radiative heat transfer
- Ventilation and infiltration

**Comment by FWuellhorst** [comment]
@larissakuehn : I would opt for the second approach. You could start by making the changes in a branch of the AixLib dependency and then check if it works with BESMod. If it does, create the PR in the AixLib. 
Especially towards the new UFH model, we have to check which way is the best to go forward with.
