### ISSUE TITLE
Heating Curve as a replaceable model

### ISSUE THREAD

**Issue by FloWill** [RWTH-EBC/BESMod#66]
To investigate different heating curves, it would be useful to make the heating curve model under "hydraulic.control" a replaceable model. 
It could also be useful to add examplary heating curve models from for example different brands.

**Comment by FWuellhorst** [comment]
I agree! Please also check the heating curve options in the AixLib. I implemented one there, but found it to hard to parametrize for BESMod. This is why I did not use it. I think heating curve options should go into the AixLib, the replaceable models in BESMod.

**Comment by tstorek** [comment]
Hi, 
I am accross the same issue. Maybe a little hint from the building automation point of view. Usually, there are different types of implementations in real systems. 

1. Using grid points to define the heating curve. This has the advantage that the user does not need to care about any gradients that are difficult to estimate. This would be possible by using 2DTables that are super easy to understand, implement, and adjust. This also allows us to define the heating limit and maximum supply temperatures. 
3. Gradient-based implementation. This is directly related to the relative heating load of a building. However, estimating the suitable gradient tends to be cumbersome and does not have any advantage over the first solution.

**Comment by FWuellhorst** [comment]
@tstorek : The AixLib models already provide option 1, even with a night-setback. 
However, I am against having this as a default option. First, the supply temperature is defined top-down. You could automatically set the grid points in relation to the maximal supply temperature, but I don't have a good reference for that. Second, the current heating curve is the theoretical optimal heating curve. Having a suboptimal one as default would open up the "the reference control is bad" discussion for all default models.

**Comment by tstorek** [comment]
@FWuellhorst I am totally fine with the approach. It was just remark from the UX-perpective. I think that `night_setback` is not considered at all. But to keep things simple this totally alright for the deafult controllers :)

**Comment by FWuellhorst** [comment]
@tstorek I agree. `night_setback` is implemented, you would have to change the `TZoneSet` input curve.
