### ISSUE TITLE
Error cloning the Buildings libary with "python install_dependencies.py full"

### ISSUE THREAD

**Issue by MaxBerktoldRWTH** [RWTH-EBC/BESMod#67]
**Describe the bug**
When executing the "python install_dependencies.py full"

**To Reproduce**
1. Clone BESMod repo
2. execute "python install_dependencies.py full"

error Code:
`Resolving deltas: 100% (79621/79621), done.
Updating files: 100% (6023/6023), done.
Switched to a new branch 'commit_3bc1bcd9'
Cloning into 'D:\PycharmProjects\BESMod\installed_dependencies\Buildings'...
remote: Enumerating objects: 348763, done.
remote: Counting objects: 100% (1120/1120), done.
remote: Compressing objects: 100% (590/590), done.
remote: Total 348763 (delta 569), reused 957 (delta 476), pack-reused 347643
Receiving objects: 100% (348763/348763), 377.73 MiB | 5.56 MiB/s, done.
Resolving deltas: 100% (238379/238379), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

error: The following untracked working tree files would be overwritten by checkout:
        .gitattributes
        .github/ISSUE_TEMPLATE/bug_report.md
        .github/ISSUE_TEMPLATE/custom-issue.md
        .github/ISSUE_TEMPLATE/feature_request.md
        .github/workflows/formatting.yml
        .gitignore
        .travis.yml
        Buildings/.copiedFiles.txt
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/ControllerChillerDXHeatingEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/ControllerEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/ControllerHeatingFan.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/Validation/ControllerChillerDXHeatingEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/Validation/ControllerEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/Validation/ControllerHeatingFan.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/Validation/package.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/Validation/package.order
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/package.mo
        Buildings/Air/Systems/SingleZone/VAV/BaseClasses/package.order
        Buildings/Air/Systems/SingleZone/VAV/ChillerDXHeatingEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/PartialOpenLoop.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/Room.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/package.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/BaseClasses/package.order
        Buildings/Air/Systems/SingleZone/VAV/Examples/ChillerDXHeatingEconomizer.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/Guideline36.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/BaseClasses/ZoneWithAHUConventional.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/BaseClasses/ZoneWithAHUG36.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/BaseClasses/package.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/BaseClasses/package.order
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/ConventionalSpring.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/ConventionalSummer.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/ConventionalWinter.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/Guideline36Spring.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/Guideline36Summer.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/Guideline36Winter.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/package.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/OptimalStart/package.order
        Buildings/Air/Systems/SingleZone/VAV/Examples/package.mo
        Buildings/Air/Systems/SingleZone/VAV/Examples/package.order
        Buildings/Air/Systems/SingleZone/VAV/package.mo
        Buildings/Air/Systems/SingleZone/VAV/package.order
        Buildings/Air/Systems/SingleZone/package.mo
        Buildings/Air/Systems/SingleZone/package.order
        Buildings/Air/Systems/package.mo
        Buildings/Air/Systems/package.order
        Buildings/Air/package.mo
        Buildings/Air/package.order
        Buildings/Airflow/Multizone/BaseClasses/Door.mo
        Buildings/Airflow/Multizone/BaseClasses/DoorDiscretized.mo
        Buildings/Airflow/Multizone/BaseClasses/ErrorControl.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/Interpolate.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/PowerLaw.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/PowerLawFixedM.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/WindPressureLowRise.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/WindPressureProfile.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/package.mo
        Buildings/Airflow/Multizone/BaseClasses/Examples/package.order
        Buildings/Airflow/Multizone/BaseClasses/PartialOneWayFlowElement.mo
        Buildings/Airflow/Multizone/BaseClasses/PowerLawResistanceParameters.mo
        Buildings/Airflow/Multizone/BaseClasses/TwoWayFlowElement.mo
        Buildings/Airflow/Multizone/BaseClasses/TwoWayFlowElementBuoyancy.mo
        Buildings/Airflow/Multizone/BaseClasses/ZonalFlow.mo
        Buildings/Airflow/Multizone/BaseClasses/interpolate.mo
        Buildings/Airflow/Multizone/BaseClasses/package.mo
        Buildings/A
error: The following untracked working tree files would be removed by checkout:
        Buildings/BoundaryConditions/SolarIrradiation/Examples/GlobalPerezTiltedSurface.mo
        Buildings/BoundaryConditions/SolarIrradiation/GlobalPerezTiltedSurface.mo
        Buildings/BoundaryConditions/WeatherData/BaseClasses/PartialConvertTime.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Controller.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Controller.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Enable.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Common.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/SeparateWithAFMS.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/SeparateWithDP.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/Common_LoopDisable.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/Common_VOut_flow.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/SeparateWithAFMS.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/SeparateWithDP.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/Validation/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Limits/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/Reliefs.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/ReturnFan.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/Validation/Reliefs.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/Validation/ReturnFan.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/Validation/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/Validation/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Modulations/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Validation/Enable_FreProSta.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Validation/Enable_TOut_hOut.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Validation/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/Validation/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Subsequences/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Validation/Controller_Disable.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Validation/Controller_Mod_DamLim.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Validation/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/Validation/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/package.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Economizers/package.order
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/FreezeProtection.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/OutdoorAirFlow/ASHRAE62_1/AHU.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/SetPoints/OutdoorAirFlow/ASHRAE62_1/SumZone.mo
        Buildings/Controls/OBC/ASHRAE/G36/AHUs/MultiZone/VAV/Se
Aborting`

**Comment by FWuellhorst** [comment]
Mhm, this is strange. Can you try to clone BESMod directly under `D:`? Or change the install-directory? I think the path could be too long for windows

**Comment by FWuellhorst** [comment]
@MaxBerktoldRWTH : Could you check if this solves your issue?

**Comment by MaxBerktoldRWTH** [comment]
That solved the problem i think. I just tried again under D:\PycharmProjects\BESMod and everything worked fine. Thanks!
