### ISSUE TITLE
Minor bug fixes

### ISSUE THREAD

**Issue by LauraMaier** [RWTH-EBC/BESMod#68]
This list contains a collection of minor bug fixes.
The list is constantly growing and will be addressed in January

**1. DHW error even though no DHW subsystem**
**Bug:**
When selecting use_dhw = false and
redeclare BESMod.Systems.Demand.DHW.TappingProfiles.calcmFlowEquDynamic calcmFlow, the model has an error even though DHW is not supposed to be used.

Model error - division by zero: (DHW.calcmFlow.division.u1) / (DHW.calcmFlow.division.u2) = (0) / (0)

Error: could not solve simplified initialization for homotopy method.
Error: Integrator failed to start model.

**Suggested solution:**
Add option for calcmFlow option for "no_DHW" or add "no_DHW" as selectable subsystem

**2. Misleading model names**
**Bug:**
All controllers in BESMod.Systems.Hydraulical.Control.Components.HeatPumpNSetController are referred to heat pumps but they are also suitable for boilers, etc.

**Suggested solution:**
Use more general names for models and packages

**Comment by FWuellhorst** [comment]
1. Should be fixed, I added an example `BESMod.Examples.DesignOptimization.BESNoDHW` to demonstrate how to simulate without dhw.
2. Renamed to `BESMod.Systems.Hydraulical.Control.Components.RelativeSpeedController` in latest release
