### ISSUE TITLE
New top-down parameters for a partial retrofitted BES

### ISSUE THREAD

**Issue by HvanderStok** [RWTH-EBC/BESMod#78]
To simulate a partially retrofitted BES, introducing new top-down parameters such as `QBuiNoRetrofit_flow_nominal` and `THydSupNoRetrofit_nominal` would be beneficial. These parameters could be utilized for further parameterization so that these subsystems are automatically designed for the non-retrofitted state of the building. All retrofitted subsystems would still use the parameters `QBui_flow_nominal` and `THydSup_nominal` of the actual building.

**Comment by FWuellhorst** [comment]
Regarding naming discussion, another option would be to use `_nominal` and `_actual`, with `_nominal` referring to the old values and `_actual`  to those which are "actually" applied in the simulation. However, I think some users may think `_actual` is referring to the dynamic variable and not the parameter. Moreover, if `_nominal` is not used for all cases as the nominal value of the simulation, this further confuse. Thus, let's stay with _design and _nominal. Either way, the documentation has to specify it clearly :)
