### ISSUE TITLE
Wind speed within heat demand calculation

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/BESMod#8]
Wind speed should be 0 m/s for heat demand calculation. 
Within all models in BESMod.Systems.Demand.Building.HeatDemand the default value is 1 m/s. 

Therefore, default in BESMod.Systems.Demand.Building.HeatDemand.PartialCalcHeatingDemand should be set to 0 m/s.

**Comment by FWuellhorst** [comment]
Correct. Out of curiosity: Do you know if this even influences the ROM model?

**Comment by larissakuehn** [comment]
I checked it and the wind speed actually does not influence the ROM at all...
