### ISSUE TITLE
Type of propogated parameter calcMethod in UFH does not match type of parameter original component

### ISSUE THREAD

**Issue by Mov0** [RWTH-EBC/BESMod#85]
**Describe the bug**
The parameter calcMethod in the component AixLib.Utilities.HeatTransfer.HeatConvInside is of type AixLib.ThermalZones.HighOrder.Components.Types.CalcMethodConvectiveHeatTransferInsideSurface. However it is propogated through BESMod.Systems.Hydraulical.Components.UFH.PanelHeatingSegment and BESMod.Systems.Hydraulical.Components.UFH.PanelHeating as Integer resulting in numerous warning when setting the transfer system to UFH. Also the orientation has to be set through a parameter of type AixLib.ThermalZones.HighOrder.Components.Types.InsideSurfaceOrientation but is currently set through an integer.

**To Reproduce**
Switch transfer system to UFH.

**Expected behavior**
Types should be matching.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/bfc8659a-c255-4775-b64f-20ca4a536a90)
![grafik](https://github.com/user-attachments/assets/827a3ec3-f28d-4732-bbf7-0fec1b818c51)

**Desktop:**
Dymola2023x, Modelica 4.0.0, Windows 10 22H2

**Comment by FWuellhorst** [comment]
This is already fixed by #82
