### ISSUE TITLE
Error in PatialCalclHeatDemand

### ISSUE THREAD

**Issue by larissakuehn** [RWTH-EBC/BESMod#9]
The following error occures within BESMod.Systems.Demand.Building.HeatDemand.PartialCalcHeatingDemand: 

"Class or component 'T_const' not found in NoUser heatDemandScenario"

This is due to the integration of the model BESMod.Systems.UserProfiles.NoUser, which is realized as followed: 

Systems.UserProfiles.NoUser heatDemandScenario(final T_const=systemParameters.TOda_nominal)
  annotation (Placement(transformation(extent={{-100,18},{-50,80}})));

The parameter T_const does not exists within the component and is also not needed. Therefore its parametrisation should just be deleted and the implementation should be changes to: 

Systems.UserProfiles.NoUser heatDemandScenario() annotation (Placement(transformation(extent={{-100,18},{-50,80}})));

**Comment by FWuellhorst** [comment]
May have been fixed by #4 . I don't get the error anymore.

**Comment by larissakuehn** [comment]
Yes, you are right, seems to be solved, I will close the issue and delete the branch.
